name: Release

on:
  push:
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: WoArchiTect

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target ${{ matrix.config.target }} --release --locked --verbose
      - name: Archive
        run: Compress-Archive -DestinationPath ./target/${{ matrix.config.target }}/release/${{ env.APP_NAME }}-${{ matrix.config.target }}.zip -Path ./target/${{ matrix.config.target }}/release/${{ env.APP_NAME}}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.config.target }}
          path: ./target/${{ matrix.config.target }}/release/${{ env.APP_NAME }}-${{ matrix.config.target }}.zip

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Resolve release files
        id: reslove-release-files
        run: |
          echo 'release_files<<EOF' >> $GITHUB_OUTPUT
          realpath *.zip >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{contains(github.ref, '-')}}
          files: ${{steps.reslove-release-files.outputs.release_files}}
